// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArjn95qtqxUxSVnEcS9-oY6F0RlzGO6gg',
    appId: '1:105941960327:web:0289cfa4e47a9a38001a22',
    messagingSenderId: '105941960327',
    projectId: 'junofast-e75d7',
    authDomain: 'junofast-e75d7.firebaseapp.com',
    databaseURL: 'https://junofast-e75d7-default-rtdb.firebaseio.com',
    storageBucket: 'junofast-e75d7.appspot.com',
    measurementId: 'G-51QTK33K70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnT2OvNbDhJBofpfEfCuip-D9jy-Rjhqc',
    appId: '1:105941960327:android:2190e9816da804fd001a22',
    messagingSenderId: '105941960327',
    projectId: 'junofast-e75d7',
    databaseURL: 'https://junofast-e75d7-default-rtdb.firebaseio.com',
    storageBucket: 'junofast-e75d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_XwNxKr5gJEWmD43WIbyFNTqGC8iT1Nw',
    appId: '1:105941960327:ios:0dcdb28128331afa001a22',
    messagingSenderId: '105941960327',
    projectId: 'junofast-e75d7',
    databaseURL: 'https://junofast-e75d7-default-rtdb.firebaseio.com',
    storageBucket: 'junofast-e75d7.appspot.com',
    iosBundleId: 'com.example.junofastVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_XwNxKr5gJEWmD43WIbyFNTqGC8iT1Nw',
    appId: '1:105941960327:ios:0dcdb28128331afa001a22',
    messagingSenderId: '105941960327',
    projectId: 'junofast-e75d7',
    databaseURL: 'https://junofast-e75d7-default-rtdb.firebaseio.com',
    storageBucket: 'junofast-e75d7.appspot.com',
    iosBundleId: 'com.example.junofastVendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArjn95qtqxUxSVnEcS9-oY6F0RlzGO6gg',
    appId: '1:105941960327:web:46fbf1881de69b79001a22',
    messagingSenderId: '105941960327',
    projectId: 'junofast-e75d7',
    authDomain: 'junofast-e75d7.firebaseapp.com',
    databaseURL: 'https://junofast-e75d7-default-rtdb.firebaseio.com',
    storageBucket: 'junofast-e75d7.appspot.com',
    measurementId: 'G-0SHEJYNC7Y',
  );
}
